apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-webapp
  template:
    metadata:
      labels:
        app: hub-webapp
    spec:
      containers:
        - name: hub-webapp
          image: ghcr.io/toandos/hub-webapp:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"